### PR TITLE
Project vs projects

### PR DESCRIPTION
**Pull request by IanLee1521**
This pull request clarifies the metadata schema w.r.t. `project` vs `projects` as well as providing information about how multiple metadata (`code.json`) files are to be combined.

### CODE REVIEW

**Comment by IanLee1521** [comment]
Thanks @lukad3! Do you know when the site will get rebuilt? Looks like it's still a few versions back: https://code.gov/#/policy-guide/docs/compliance/inventory-code

**Comment by lukad03** [comment]
@IanLee1521 I plan on rebuilding soon, but am working on some major search functionality that has taken precedence.

Also, the changes you've been dropping into the `md` files were created by @mattbailey0 to guide the creation of the content and store it on GH. To change the actual content on the site, you'll need to submit PRs to change the `.template.html` files in the `components/policy-guide/.../.../` directories.

**Comment by IanLee1521** [comment]
Thanks @lukad03 . Do you know (maybe this is more for @mattbailey0) if there is something automated to regenerate the `.template.html` files, or would I need to update those files manually?

**Comment by ckaran** [comment]
I've noticed that there appear to be two very similar files that both define the schema:

https://github.com/presidential-innovation-fellows/code-gov-web/blob/master/src/app/components/policy-guide/docs/compliance/compliance-inventory-code/compliance-inventory-code.template.html

and

https://github.com/presidential-innovation-fellows/code-gov-web/blob/master/src/app/components/policy-guide/docs/compliance/compliance-metadata-schema/compliance-metadata-schema.template.html

I suspect that one of them is leftovers from code motion.  Can you delete whatever is not longer current?

**Pull request merged**
