### PR TITLE
style updates to browse, search, project details, and home

### PR DESCRIPTION
**Pull request by jlow81**
**Summary**

Style updates across Home, Browse Projects, Search Results, and Project Details

**Home Search Description and Browse Projects Dropdown** 
Before
image

After
image
***
**Browse and Search Page Search Go Button - Remove Border**
Before
image

After
image
***
**Browse and Search Sort Dropdown**
Before
image

After
image
***
**Tightened Up Spacing in Browse Projects and Search Results**
Before
image

After
image
***
**Increased Font Size of Pagination**
Before
image

After
image
***
**Tightened Up Spacing on Project Details Page**
Before
image

After
image

Explain the **motivation** for making this change. What existing problem does the pull request solve?

This PR fixing styling issues across Home, Browse Projects, Search Results, and Project Details

### CODE REVIEW

**Comment by DanielJDufour** [comment]
This looks awesome.  I'll make sure to include it in the rearchitecture.

**Comment by DanielJDufour** [comment]
I'm looking at this now

**Comment by DanielJDufour** [comment]
This has been copied over

**Comment by jlow81** [comment]
@DanielJDufour has this been moved to staging?

**Comment by jlow81** [comment]
https://github.com/GSA/caribou/issues/55 is still not resolved

**Comment by saracope** [comment]
Closing this out since these changes have been integrated into the React FE.

**Pull request closed without merging**
