### PR TITLE
Updated name of NASA to fully spelled out

### PR DESCRIPTION
**Pull request by IanLee1521**
Signed-off-by: Ian Lee <lee1001@llnl.gov>

### CODE REVIEW

**Comment by michaelhwan** [comment]
@IanLee1521 I just noticed NASA wasn't spelled out so I'll make that change as well.

**Comment by IanLee1521** [comment]
@michaelhwan -- Or you can just leave it as two separate requests. Not sure if @lukad03 /  @okamanda  / @mattbailey0 have an opinion on that.

**Comment by michaelhwan** [comment]
@IanLee1521 I'll leave it.

**Comment by lukad03** [comment]
@IanLee1521 I'd like to follow up with @mattbailey0 and possibly a rep from NASA to see what their preference is. NASA seems to be the exception when it comes to what the general population knows them best by, so I'd like to use the most recognizable name and am willing to break with convention to do so.

**Comment by jbjonesjr** [comment]
cc/ @jasonduley

**Comment by jasonduley** [comment]
Sorry for the lapse in response.  NASA is fine with us!

**Comment by jbjonesjr** [comment]
@IanLee1521 I think we can close this PR now based on @jasonduley comment

**Comment by IanLee1521** [comment]
Sounds good. The purist in me would like them all one way or the other, but I'm not against it.

**Pull request closed without merging**
