### PR TITLE
Include source policy on code.gov (#33)

### PR DESCRIPTION
**Pull request by PhilipBale**
Including policy on website after speaking with @AlvandSalehi.  Mostly content inclusion and adding libraries for html anchors.

https://github.com/presidential-innovation-fellows/code-gov-web/issues/33

### CODE REVIEW

**Comment by PhilipBale** [comment]
At @okamanda I'm getting an issue w/ circle saying: 'No CODECLIMATE_REPO_TOKEN found. A CODECLIMATE_REPO_TOKEN must be specified as an environment variable.'

**Comment by okamanda** [comment]
@PhilipBale Do you have access to code-gov-web on CodeClimate?

**Comment by PhilipBale** [comment]
@okamanda I only have access to my fork

**Comment by PhilipBale** [comment]
@okamanda circle issues fixed--I don't seem to have access to the federalist though and can't see its errors.

**Comment by okamanda** [comment]
Let me look into federalist access

--

olivier kamanda
white house presidential innovation fellow
e: olivier.kamanda@pif.gov
t: @kamanda
w: pif.gov

On Jun 12, 2017, at 3:10 PM, Philip Bale <notifications@github.com> wrote:

@okamanda <https://github.com/okamanda> circle issues fixed--I don't seem
to have access to the federalist though and can't see its errors.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/presidential-innovation-fellows/code-gov-web/pull/248#issuecomment-307890234>,
or mute the thread

**Pull request closed without merging**
