### PR TITLE
reorder agencies by alphabetical order

### PR DESCRIPTION
**Pull request by michaelhwan**

### CODE REVIEW

**Comment by michaelhwan** [comment]
@IanLee1521 thanks for catching this error Ian!

**Comment by IanLee1521** [comment]
No worries! You probably didn't mean to close this though?

**Comment by michaelhwan** [comment]
@IanLee1521 I'm going to redo the pull request. I also forgot to create a new branch.

**Comment by IanLee1521** [comment]
Sounds good.

By the way, you might also like: #147

**Pull request closed without merging**
